stages:
  - build
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - docker build --build-arg $API_TOKEN --build-arg $CONNECT_PATH -t $IMAGE .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $IMAGE

deploy:
  stage: deploy
  when: manual
  environment:
    name: ruprod
  before_script:
    - !reference [ .deploy-registry-creds ]
  script:
    - cd .kube
    - kustomize edit set namespace $KUBE_NAMESPACE
    - kustomize build | envsubst | kubectl apply -f -
